version: '3.5'
services:
  pycsw:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: met-pycsw-container
    image: metno/met-pycsw-container
    ports:
      - "5555:8000"
    environment:
      INDEXDB: "false"
      METADATA: "/home/pycsw/sample_data/xml/adc/XML"
      OUTPUT_ISO: "/home/pycsw/sample_data/iso_xml/adc"
      FIX: "false"
    restart: unless-stopped
    #depends_on:
    #  - "postgres"
    volumes:
      - ./volumes/conf/pycsw.cfg:/etc/pycsw/pycsw.cfg
      - ./volumes/commands/pycsw_setup.sh:/usr/local/bin/pycsw_setup.sh
      - ./volumes/commands/mmd2isofix.py:/usr/local/bin/mmd2isofix.py
      - ./volumes/commands/mmd-to-iso.xsl:/usr/local/share/mmd-to-iso.xsl
      - ./volumes/sample_data:/home/pycsw/sample_data
    entrypoint:
      - /bin/sh
      - /usr/local/bin/pycsw_setup.sh
